id: IE91E29F9
source: https://www.lotsawahouse.org
source_file: null
initial_creation_type: input
imported: '2022-05-31T05:01:00.969232'
last_modified: '2022-05-31T05:01:00.969237'
parser: null
source_metadata:
  title: Lama Zhang Tsöndrü Drakpa
  language: bo
  description: 'Texts by and about Lama Zhang Tsöndrü Drakpa (bla ma zhang brtson
    ''grus grags pa, 1123–1193), founder of the Tsalpa Kagyü:'
  volume:
    fAB99:
      title: Twelve and a Half Crippled Verses
      base_file: fAB99.txt
      order: 1
      parent: Songs and Poems
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
